name: Build Activation Radar
on:
  schedule: [{ cron: "0 8 * * 1" }]  # Mondays 08:00 UTC
  workflow_dispatch:                  # run it manually from the Actions tab

permissions:
  contents: write   # allow the bot to commit artifacts back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate artifacts
        run: |
          python -m src.radar_cli --geo US --keywords "sneakers,laptops,furniture,cosmetics,groceries" --timeframe "today 5-y"
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/trends_signals.csv reports/activation_radar.xlsx assets/*.png || true
          git commit -m "ci: weekly radar refresh" || echo "No changes"
          git push
